export default function () {
  return {
    config: {}, dailySchedule: {},
    inStatus: '',
    outStatus: '',
    canInAbsent: false,
    canOutAbsent: false,
    isLate: false,
    showPresenceDialog: false,
    presenceType: '',
    presenceSuccess: false,
    absenceIn: {},
    absenceOut: {},
    base64String: '',
    activeDate: '',
    current: 1,
    inPhotoURL: '',
    outPhotoURL: '',
    showPresenceDetail: false,
    showPermitForm: false,
    disableSaveButton: true,
    permitError: {},
    saveStatus: 500,
    showPermitDetail: false, deleteConfirm: false,
    permitDetail: {}, selectedPermission: null,
    period: '01-2022',
    // date range
    dateRangeStart: '',
    dateRangeEnd: '',
    presenceDetail: {},
    presenceConfig: {
      intime: 'HH:mm',
      outtime: 'HH:mm',
      lat: '', long: '',
      tolerance: 0,
      range: 0
    },
    configError: {}, notifCounter: 0,
    scheduleDays: {}, staffName: '', showScheduleForm: false,
    staffId: '', requiredPresent: 'wajib',
    userEvents: [], agendaId: null,
    allEvents: [],
  }
}
